HOUR_IN_MINUTES = 60
DAY_IN_HOURS = 24
WEEK_IN_DAYS = 7
DAY_IN_MINUTES = DAY_IN_HOURS * HOUR_IN_MINUTES
WEEK_IN_HOURS = WEEK_IN_DAYS * DAY_IN_HOURS
WEEK_IN_MINUTES = HOUR_IN_MINUTES * DAY_IN_HOURS * WEEK_IN_DAYS
